package com.kg.testjsfa8h4.entity;
// Generated Dec 8, 2016 10:35:31 AM by Hibernate Tools 3.2.1.GA



/**
 * Access generated by hbm2java
 */
public class Access  implements java.io.Serializable {


     private Integer id;
     private String privelege;
     private String description;

    public Access() {
    }

    public Access(String privelege, String description) {
       this.privelege = privelege;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPrivelege() {
        return this.privelege;
    }
    
    public void setPrivelege(String privelege) {
        this.privelege = privelege;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


