package com.kg.testjsfa8h4.entity;
// Generated Dec 8, 2016 10:35:31 AM by Hibernate Tools 3.2.1.GA



/**
 * EmployesList generated by hbm2java
 */
public class EmployesList  implements java.io.Serializable {


     private Integer id;
     private String idForm1;
     private String fio;
     private String phoneHome;
     private String phoneMobile;
     private String phoneWork;
     private String homeAddress;
     private String mail;
     private String bankDetails;
     private String position;

    public EmployesList() {
    }

    public EmployesList(String idForm1, String fio, String phoneHome, String phoneMobile, String phoneWork, String homeAddress, String mail, String bankDetails, String position) {
       this.idForm1 = idForm1;
       this.fio = fio;
       this.phoneHome = phoneHome;
       this.phoneMobile = phoneMobile;
       this.phoneWork = phoneWork;
       this.homeAddress = homeAddress;
       this.mail = mail;
       this.bankDetails = bankDetails;
       this.position = position;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIdForm1() {
        return this.idForm1;
    }
    
    public void setIdForm1(String idForm1) {
        this.idForm1 = idForm1;
    }
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }
    public String getPhoneHome() {
        return this.phoneHome;
    }
    
    public void setPhoneHome(String phoneHome) {
        this.phoneHome = phoneHome;
    }
    public String getPhoneMobile() {
        return this.phoneMobile;
    }
    
    public void setPhoneMobile(String phoneMobile) {
        this.phoneMobile = phoneMobile;
    }
    public String getPhoneWork() {
        return this.phoneWork;
    }
    
    public void setPhoneWork(String phoneWork) {
        this.phoneWork = phoneWork;
    }
    public String getHomeAddress() {
        return this.homeAddress;
    }
    
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getBankDetails() {
        return this.bankDetails;
    }
    
    public void setBankDetails(String bankDetails) {
        this.bankDetails = bankDetails;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


