package com.kg.testjsfa8h4.entity;
// Generated Dec 14, 2016 1:26:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployesList generated by hbm2java
 */
@Entity
@Table(name="employes_list"
    ,catalog="testjsfa8h4"
)
public class EmployesList  implements java.io.Serializable {


     private Integer id;
     private String idForm1;
     private String fio;
     private String phoneHome;
     private String phoneMobile;
     private String phoneWork;
     private String homeAddress;
     private String mail;
     private String bankDetails;
     private String position;

    public EmployesList() {
    }

    public EmployesList(String idForm1, String fio, String phoneHome, String phoneMobile, String phoneWork, String homeAddress, String mail, String bankDetails, String position) {
       this.idForm1 = idForm1;
       this.fio = fio;
       this.phoneHome = phoneHome;
       this.phoneMobile = phoneMobile;
       this.phoneWork = phoneWork;
       this.homeAddress = homeAddress;
       this.mail = mail;
       this.bankDetails = bankDetails;
       this.position = position;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ID_FORM1", nullable=false, length=10)
    public String getIdForm1() {
        return this.idForm1;
    }
    
    public void setIdForm1(String idForm1) {
        this.idForm1 = idForm1;
    }

    
    @Column(name="FIO", nullable=false, length=200)
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }

    
    @Column(name="PHONE_HOME", nullable=false, length=50)
    public String getPhoneHome() {
        return this.phoneHome;
    }
    
    public void setPhoneHome(String phoneHome) {
        this.phoneHome = phoneHome;
    }

    
    @Column(name="PHONE_MOBILE", nullable=false, length=50)
    public String getPhoneMobile() {
        return this.phoneMobile;
    }
    
    public void setPhoneMobile(String phoneMobile) {
        this.phoneMobile = phoneMobile;
    }

    
    @Column(name="PHONE_WORK", nullable=false, length=50)
    public String getPhoneWork() {
        return this.phoneWork;
    }
    
    public void setPhoneWork(String phoneWork) {
        this.phoneWork = phoneWork;
    }

    
    @Column(name="HOME_ADDRESS", nullable=false, length=200)
    public String getHomeAddress() {
        return this.homeAddress;
    }
    
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    
    @Column(name="MAIL", nullable=false, length=50)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="BANK_DETAILS", nullable=false, length=200)
    public String getBankDetails() {
        return this.bankDetails;
    }
    
    public void setBankDetails(String bankDetails) {
        this.bankDetails = bankDetails;
    }

    
    @Column(name="POSITION", nullable=false, length=200)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


