package com.kg.testjsfa8h4.entity;
// Generated Dec 8, 2016 10:35:31 AM by Hibernate Tools 3.2.1.GA



/**
 * Form1Files generated by hbm2java
 */
public class Form1Files  implements java.io.Serializable {


     private Integer id;
     private int idForm1;
     private String fileName;
     private String fileDate;
     private String fileData;

    public Form1Files() {
    }

    public Form1Files(int idForm1, String fileName, String fileDate, String fileData) {
       this.idForm1 = idForm1;
       this.fileName = fileName;
       this.fileDate = fileDate;
       this.fileData = fileData;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdForm1() {
        return this.idForm1;
    }
    
    public void setIdForm1(int idForm1) {
        this.idForm1 = idForm1;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFileDate() {
        return this.fileDate;
    }
    
    public void setFileDate(String fileDate) {
        this.fileDate = fileDate;
    }
    public String getFileData() {
        return this.fileData;
    }
    
    public void setFileData(String fileData) {
        this.fileData = fileData;
    }




}


