package com.kg.testjsfa8h4.entity;
// Generated Dec 14, 2016 1:26:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Form1Files generated by hbm2java
 */
@Entity
@Table(name="form1_files"
    ,catalog="testjsfa8h4"
)
public class Form1Files  implements java.io.Serializable {


     private Integer id;
     private int idForm1;
     private String fileName;
     private String fileDate;
     private String fileData;

    public Form1Files() {
    }

    public Form1Files(int idForm1, String fileName, String fileDate, String fileData) {
       this.idForm1 = idForm1;
       this.fileName = fileName;
       this.fileDate = fileDate;
       this.fileData = fileData;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ID_FORM1", nullable=false)
    public int getIdForm1() {
        return this.idForm1;
    }
    
    public void setIdForm1(int idForm1) {
        this.idForm1 = idForm1;
    }

    
    @Column(name="FILE_NAME", nullable=false, length=50)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="FILE_DATE", nullable=false, length=50)
    public String getFileDate() {
        return this.fileDate;
    }
    
    public void setFileDate(String fileDate) {
        this.fileDate = fileDate;
    }

    
    @Column(name="FILE_DATA", nullable=false, length=50)
    public String getFileData() {
        return this.fileData;
    }
    
    public void setFileData(String fileData) {
        this.fileData = fileData;
    }




}


