package com.kg.testjsfa8h4.entity;
// Generated Dec 12, 2016 1:39:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="testjsfa8h4"
)
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String privelege;
     private String description;

    public Groups() {
    }

    public Groups(String privelege, String description) {
       this.privelege = privelege;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="PRIVELEGE", nullable=false, length=10)
    public String getPrivelege() {
        return this.privelege;
    }
    
    public void setPrivelege(String privelege) {
        this.privelege = privelege;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=10)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


