package com.kg.testjsfa8h4.entity;
// Generated Dec 8, 2016 10:35:31 AM by Hibernate Tools 3.2.1.GA



/**
 * LegalForm generated by hbm2java
 */
public class LegalForm  implements java.io.Serializable {


     private Integer id;
     private String legalForm;

    public LegalForm() {
    }

    public LegalForm(String legalForm) {
       this.legalForm = legalForm;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLegalForm() {
        return this.legalForm;
    }
    
    public void setLegalForm(String legalForm) {
        this.legalForm = legalForm;
    }




}


