package com.kg.testjsfa8h4.entity;
// Generated Dec 12, 2016 1:39:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LegalForm generated by hbm2java
 */
@Entity
@Table(name="legal_form"
    ,catalog="testjsfa8h4"
)
public class LegalForm  implements java.io.Serializable {


     private Integer id;
     private String legalForm;

    public LegalForm() {
    }

    public LegalForm(String legalForm) {
       this.legalForm = legalForm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="LEGAL_FORM", nullable=false, length=100)
    public String getLegalForm() {
        return this.legalForm;
    }
    
    public void setLegalForm(String legalForm) {
        this.legalForm = legalForm;
    }




}


