package com.kg.testjsfa8h4.entity;
// Generated Dec 15, 2016 10:08:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LegalForm generated by hbm2java
 */
@Entity
@Table(name="legal_form"
    ,catalog="testjsfa8h4"
)
public class LegalForm  implements java.io.Serializable {


     private Integer id;
     private String legalForm;
     private Set form1s = new HashSet(0);

    public LegalForm() {
    }

	
    public LegalForm(String legalForm) {
        this.legalForm = legalForm;
    }
    public LegalForm(String legalForm, Set form1s) {
       this.legalForm = legalForm;
       this.form1s = form1s;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="LEGAL_FORM", nullable=false, length=200)
    public String getLegalForm() {
        return this.legalForm;
    }
    
    public void setLegalForm(String legalForm) {
        this.legalForm = legalForm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="legalForm")
    public Set getForm1s() {
        return this.form1s;
    }
    
    public void setForm1s(Set form1s) {
        this.form1s = form1s;
    }




}


