package com.kg.testjsfa8h4.entity;
// Generated Dec 15, 2016 10:08:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OwnType generated by hbm2java
 */
@Entity
@Table(name="own_type"
    ,catalog="testjsfa8h4"
)
public class OwnType  implements java.io.Serializable {


     private Integer id;
     private String ownType;
     private Set form1s = new HashSet(0);

    public OwnType() {
    }

	
    public OwnType(String ownType) {
        this.ownType = ownType;
    }
    public OwnType(String ownType, Set form1s) {
       this.ownType = ownType;
       this.form1s = form1s;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="OWN_TYPE", nullable=false, length=200)
    public String getOwnType() {
        return this.ownType;
    }
    
    public void setOwnType(String ownType) {
        this.ownType = ownType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ownType")
    public Set getForm1s() {
        return this.form1s;
    }
    
    public void setForm1s(Set form1s) {
        this.form1s = form1s;
    }




}


