package com.kg.testjsfa8h4.entity;
// Generated Dec 14, 2016 1:26:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OwnType generated by hbm2java
 */
@Entity
@Table(name="own_type"
    ,catalog="testjsfa8h4"
)
public class OwnType  implements java.io.Serializable {


     private Integer id;
     private String ownType;

    public OwnType() {
    }

    public OwnType(String ownType) {
       this.ownType = ownType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="OWN_TYPE", nullable=false, length=200)
    public String getOwnType() {
        return this.ownType;
    }
    
    public void setOwnType(String ownType) {
        this.ownType = ownType;
    }




}


