package com.kg.testjsfa8h4.entity;
// Generated Dec 14, 2016 1:26:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="testjsfa8h4"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private Groups groups;
     private String login;
     private String password;
     private String fio;
     private String phoneNumber;
     private String email;
     private Date createDate;
     private Date loginDate;

    public Users() {
    }

	
    public Users(Groups groups, String login, String password, String fio, Date createDate) {
        this.groups = groups;
        this.login = login;
        this.password = password;
        this.fio = fio;
        this.createDate = createDate;
    }
    public Users(Groups groups, String login, String password, String fio, String phoneNumber, String email, Date createDate, Date loginDate) {
       this.groups = groups;
       this.login = login;
       this.password = password;
       this.fio = fio;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.createDate = createDate;
       this.loginDate = loginDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ACCESS", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    
    @Column(name="LOGIN", nullable=false, length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FIO", nullable=false, length=200)
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }

    
    @Column(name="PHONE_NUMBER", length=50)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOGIN_DATE", length=19)
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }




}


