package com.kg.testjsfa8h4.entity;
// Generated Dec 8, 2016 10:35:31 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String idAccess;
     private String fio;
     private String phoneNumber;
     private String email;
     private Date createDate;
     private Date loginDate;

    public Users() {
    }

	
    public Users(String login, String idAccess, String fio, Date createDate, Date loginDate) {
        this.login = login;
        this.idAccess = idAccess;
        this.fio = fio;
        this.createDate = createDate;
        this.loginDate = loginDate;
    }
    public Users(String login, String idAccess, String fio, String phoneNumber, String email, Date createDate, Date loginDate) {
       this.login = login;
       this.idAccess = idAccess;
       this.fio = fio;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.createDate = createDate;
       this.loginDate = loginDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getIdAccess() {
        return this.idAccess;
    }
    
    public void setIdAccess(String idAccess) {
        this.idAccess = idAccess;
    }
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }




}


